### ISSUE TITLE
怎么控制只识别框范围里的二维码呢？

### ISSUE THREAD

**Issue by zeroBugL** [jenly1314/WeChatQRCode#10]
怎么控制只识别框范围里的二维码呢？

**Comment by jenly1314** [comment]
自定义实现一个 Analyzer，截取部分预览区域进行识别，实现逻辑处理可参考：[AreaRectAnalyzer](https://github.com/jenly1314/ZXingLite/blob/master/zxing-lite/src/main/java/com/king/zxing/analyze/AreaRectAnalyzer.java)
