### ISSUE TITLE
java版本加载dll文件出错，java.lang.UnsatisfiedLinkError: F:\ocr\WeChatQRCode\lib\libopencv_java452.dll: Can't find dependent libraries

### ISSUE THREAD

**Issue by buliugu** [jenly1314/WeChatQRCode#11]
![image](https://user-images.githubusercontent.com/3390134/144701989-2f47e78c-1335-44a0-baba-77ffb00c7abe.png)
dll与jar文件均已复制到lib下，运行后报错

**Comment by z4265826** [comment]
解决了吗？请问是怎么解决的呀？
