### ISSUE TITLE
怎么通过返回的二维码各个顶点定位位置啊？

### ISSUE THREAD

**Issue by shaoguanglin** [jenly1314/WeChatQRCode#14]
扫描返回的结果{"points":[{"nativeObj":542547384896},{"nativeObj":538574786560}],"bitmap":{"mHeight":640,"mNativePtr":540016003392,"mWidth":480},"result":["https://cloud.tencent.com/weappAuthLogin?token\xxxxxx","http://weixin.qq.com/x/xxxxxx"]}  这个points返回的结果是Mat类型 需要怎么转成坐标呢？

**Comment by shaoguanglin** [comment]
已解决

**Comment by Kent-GitHub** [comment]
> 
怎么解决的，能分享一下吗
