### ISSUE TITLE
face-tracker-v001这个文件拷贝不下来，所以扫描WeChatQRCodeDetector.init()会无法初始化sWeChatQRCode，以至于无法扫描

### ISSUE THREAD

**Issue by leikai** [jenly1314/WeChatQRCode#17]

**Comment by leikai** [comment]
![image](https://user-images.githubusercontent.com/34222577/165247241-af579ca2-0baf-460b-a7db-7d001ead1284.png)

**Comment by jenly1314** [comment]
**WeChatQRCodeDetector** 中并未用到 **face-tracker-v001** 这个文件，也没有这个文件，请确认下是否是其他第三方依赖的文件，也放入了 models目录下。
