### ISSUE TITLE
可以再给微信的OpenCV编译一个arm64的库么？

### ISSUE THREAD

**Issue by asdzheng** [jenly1314/WeChatQRCode#2]

**Comment by jenly1314** [comment]
一个 **armeabi-v7a** 的so库就有十多兆，再加个 **arm64-v8a** 的话，最终的APK包就更大了。因为一个扫码功能增加二十多兆的APK体积，感觉没太大必要，因为 **armeabi-v7a**本身是兼容 **arm64-v8a** 的。在多架构适配与APK体积大小之间得有所取舍。

**Comment by asdzheng** [comment]
如果商家国外市场的话是需要arm64-v8a的，用app bundle上架的话并不会增加包大小

**Comment by jenly1314** [comment]
通过app bundle的方式上架发布确实可以解决这个这问题。（如果确实有需要的话，我抽空再编译一下。）

**Comment by asdzheng** [comment]
确实是需要呀，要不你把编译的方式发下，我自己试试看能不能编译出来

**Comment by asdzheng** [comment]
已自己编译出来
