### ISSUE TITLE
opencv的版本，我看是4.6.0, 想更换到4.5.5， 有教程吗？

### ISSUE THREAD

**Issue by 307509256** [jenly1314/WeChatQRCode#22]

**Comment by 307509256** [comment]
已解决，就是要注意把contrib的源码里，屏蔽下模型assert的4个地方

**Comment by 307509256** [comment]
@jenly1314   不过我编译出来的so库有26M，我看群主编译的只有17M，是不是哪个编译选项需要调下？

**Comment by jayclin** [comment]
怎么编译的新的so文件啊，我用官方的会报错

**Comment by jenly1314** [comment]
[opencv_contrib](https://github.com/opencv/opencv_contrib)
