### ISSUE TITLE
项目一跑起来就报这个错是为啥呢？

### ISSUE THREAD

**Issue by Selina592732122** [jenly1314/WeChatQRCode#25]
java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.wechat_qrcode.WeChatQRCode.WeChatQRCode_0(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (tried Java_org_opencv_wechat_1qrcode_WeChatQRCode_WeChatQRCode_10 and Java_org_opencv_wechat_1qrcode_WeChatQRCode_WeChatQRCode_10__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)

<img width="1452" alt="image" src="https://user-images.githubusercontent.com/8281419/192984870-d1d10241-feb2-40ad-bbf0-b2cc9a04f50b.png">

**Comment by YhDyhd0** [comment]
gradle重新  clean  build  ->  opencv和app2个模块

**Comment by jenly1314** [comment]
[![Download](https://img.shields.io/badge/download-App-blue.svg)](https://raw.githubusercontent.com/jenly1314/WeChatQRCode/master/app/release/app-release.apk) [![CI](https://github.com/jenly1314/WeChatQRCode/workflows/Android%20CI/badge.svg)](https://github.com/jenly1314/WeChatQRCode/actions)

**Comment by Selina592732122** [comment]
谢谢您的邮件！
O(∩_∩)O~

**Comment by jenly1314** [comment]
#26 重新构建一下 ：**Build** -> **Rebuild Project**
