### ISSUE TITLE
项目运行直接闪退了

### ISSUE THREAD

**Issue by chengkaizone** [jenly1314/WeChatQRCode#26]
项目运行直接闪退了，我特意清理了项目并重启了工具还是如此
报错如下
<img width="1301" alt="截屏2022-12-04 11 47 21" src="https://user-images.githubusercontent.com/6120008/205473349-30c34234-ee45-4842-88e7-212ea8329fb0.png">

**Comment by jenly1314** [comment]
[![CI](https://github.com/jenly1314/WeChatQRCode/workflows/Android%20CI/badge.svg)](https://github.com/jenly1314/WeChatQRCode/actions)

**Comment by LiWeiQiangAndroid** [comment]
一样错误

**Comment by jenly1314** [comment]
重新构建一下 ：**Build** -> **Rebuild Project**

**Comment by mainlxl** [comment]
少了依赖 缺少so的那个依赖
