### ISSUE TITLE
识别图片二维码崩溃

### ISSUE THREAD

**Issue by chengongyi** [jenly1314/WeChatQRCode#31]
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x78aabeb000
    x0  0000000000000991  x1  0000000000000863  x2  00000000000006ea  x3  00000078a4c042a4
    x4  0000000000000001  x5  00000078b5502153  x6  00000000000009b9  x7  0000000000000001
    x8  00000078a4e00000  x9  00000000086506e9  x10 000000000177ac01  x11 000000000177ac00
    x12 00000078b4400000  x13 00000078a6600000  x14 0000000000000002  x15 000000000177abff
    x16 000000000071d39c  x17 0000000000503b13  x18 00000078b65f0000  x19 0000007b97f854c0
    x20 0000000000000865  x21 000000000050551e  x22 00000000000006ea  x23 000000000071d39b
    x24 00000000000006e9  x25 0000000000000004  x26 0000007972ebc928  x27 0000000000000865
    x28 00000000000006e9  x29 0000007ba1c4ff00
    sp  0000007ba1c4fe90  lr  0000007972623490  pc  00000079726234f0

backtrace:
    #00 pc 00000000008a04f0  /data/data/com.lianjia.alliance/app_p_n/636038542/libopencv_java4.so
    #01 pc 00000000008a035c  /data/data/com.lianjia.alliance/app_p_n/636038542/libopencv_java4.so
    #02 pc 00000000008b082c  /data/data/com.lianjia.alliance/app_p_n/636038542/libopencv_java4.so
    #03 pc 00000000008a8a88  /data/data/com.lianjia.alliance/app_p_n/636038542/libopencv_java4.so
    #04 pc 00000000008d4e50  /data/data/com.lianjia.alliance/app_p_n/636038542/libopencv_java4.so
    #05 pc 00000000008d495c  /data/data/com.lianjia.alliance/app_p_n/636038542/libopencv_java4.so
    #06 pc 00000000008869dc  /data/data/com.lianjia.alliance/app_p_n/636038542/libopencv_java4.so
    #07 pc 0000000000886544  /data/data/com.lianjia.alliance/app_p_n/636038542/libopencv_java4.so
    #08 pc 0000000000889ac0  /data/data/com.lianjia.alliance/app_p_n/636038542/libopencv_java4.so (_ZN2cv13wechat_qrcode12WeChatQRCode4Impl6decodeERKNS_3MatERNSt6__ndk16vectorIS3_NS6_9allocatorIS3_EEEESB_+524)
    #09 pc 0000000000889388  /data/data/com.lianjia.alliance/app_p_n/636038542/libopencv_java4.so (_ZN2cv13wechat_qrcode12WeChatQRCode15detectAndDecodeERKNS_11_InputArrayERKNS_12_OutputArrayE+348)
    #10 pc 000000000023e320  /data/data/com.lianjia.alliance/app_p_n/636038542/libopencv_java4.so (Java_org_opencv_wechat_1qrcode_WeChatQRCode_detectAndDecode_11+80)
    #11 pc 0000000000150354  /apex/com.android.runtime/lib64/libart.so
    #12 pc 00000000001475bc  /apex/com.android.runtime/lib64/libart.so
    #13 pc 00000000001561d8  /apex/com.android.runtime/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+288)
    #14 pc 00000000002fd904  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPNS_11ShadowFrameEtPNS_6JValueE+388)
    #15 pc 00000000002f8bd4  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+916)
    #16 pc 00000000005ce120  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+372)
    #17 pc 0000000000141998  /apex/com.android.runtime/lib64/libart.so
    #18 pc 00000000005cb878  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1436)
    #19 pc 0000000000141818  /apex/com.android.runtime/lib64/libart.so
    #20 pc 00000000005ce420  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1140)
    #21 pc 0000000000141998  /apex/com.android.runtime/lib64/libart.so
    #22 pc 00000000005ce420  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1140)
    #23 pc 0000000000141998  /apex/com.android.runtime/lib64/libart.so
    #24 pc 00000000005ce420  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1140)
    #25 pc 0000000000141998  /apex/com.android.runtime/lib64/libart.so
    #26 pc 00000000002ce230  /apex/com.android.runtime/lib64/libart.so
    #27 pc 00000000005bc0a8  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1016)
    #28 pc 000000000015046c  /apex/com.android.runtime/lib64/libart.so
    #29 pc 00000000001475bc  /apex/com.android.runtime/lib64/libart.so
    #30 pc 00000000001561d8  /apex/com.android.runtime/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+288)
    #31 pc 00000000004d8838  /apex/com.android.runtime/lib64/libart.so
    #32 pc 00000000004da260  /apex/com.android.runtime/lib64/libart.so (_ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_m+1480)
    #33 pc 0000000000464144  /apex/com.android.runtime/lib64/libart.so
    #34 pc 00000000000f8c38  /system/framework/arm64/boot.oat

**Comment by jenly1314** [comment]
* 建议先使用 [演示App](https://raw.githubusercontent.com/jenly1314/WeChatQRCode/master/app/release/app-release.apk) 测试下看是否正常，以此来排除外部因素干扰的可能。
* 如果使用 [演示App](https://raw.githubusercontent.com/jenly1314/WeChatQRCode/master/app/release/app-release.apk) 依旧能复现此问题，劳烦提供测试时的设备型号、系统版本和日志相关信息。

**Comment by chengongyi** [comment]
> * 建议先使用 [演示App](https://raw.githubusercontent.com/jenly1314/WeChatQRCode/master/app/release/app-release.apk) 测试下看是否正常，以此来排除外部因素干扰的可能。
> * 如果使用 [演示App](https://raw.githubusercontent.com/jenly1314/WeChatQRCode/master/app/release/app-release.apk) 依旧能复现此问题，劳烦提供测试时的设备型号、系统版本和日志相关信息。

不是必现问题，但是出现频率较高
