### ISSUE TITLE
扫这个图必崩溃

### ISSUE THREAD

**Issue by mosentest** [jenly1314/WeChatQRCode#36]
![image](https://github.com/jenly1314/WeChatQRCode/assets/3632260/3c793728-856d-4e71-9ad8-72efb2a49a8b)
<img width="1073" alt="image" src="https://github.com/jenly1314/WeChatQRCode/assets/3632260/8b983c55-9a4a-4b7b-a155-02db4fd45cc7">

**Comment by mosentest** [comment]
JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0xc6
    string: '������Ů'

乱码引起的，希望能修复下

**Comment by mosentest** [comment]
@jenly1314 希望能改下，这个问题比较严重
https://blog.csdn.net/liuzehn/article/details/89852076

**Comment by mosentest** [comment]
最好33和33之前的都做个修复版本，源码上没wechat的c++代码，不好二次开发，建议放上来，可以给其他人帮忙解决

**Comment by mosentest** [comment]
理我好不好，一天过去了

**Comment by mosentest** [comment]
。。。

**Comment by JasonYinH** [comment]
还没理你，五个月了

**Comment by SimbaLiu** [comment]
我也遇到了同样的问题，调用WeChatQRCode.detectAndDecode()方法在识别相册中选择的包含中文的二维码时，荣耀手机没问题，OPPO手机如OPPO Reno11Pro(PJJ110)、Reno2Z(PCKM80)会报JNI编码错误。
