### ISSUE TITLE
和Linphone项目的libc++_shared.so文件冲突

### ISSUE THREAD

**Issue by lantee** [jenly1314/WeChatQRCode#37]
2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
 - C:\Users\lante\.gradle\caches\transforms-3\d34c9e1235017dc17697b3298e6461e9\transformed\jetified-opencv-1.3.0\jni\arm64-v8a\libc++_shared.so
 - C:\Users\lante\.gradle\caches\transforms-3\bd0535683786c3682061e179655a41c1\transformed\jetified-linphone-sdk-android-debug-5.2.38\jni\arm64-v8a\libc++_shared.so
 - 两个文件都是必须的 反正都会引起崩溃 如何解决

**Comment by jenly1314** [comment]
这种冲突的情况，可以通过 `packagingOptions`  配置选取第一个试试。
```
packagingOptions {
    pickFirst "*/libc++_shared.so"
}
```

**Comment by lantee** [comment]
这个方法我试过了 可以运行 但是使用linphone相关功能会引起崩溃。
libc++_shared.so 怀疑是两个库的文件名重合 但是内容不一样导致的

**Comment by lantee** [comment]
似乎是编译输出so文件用的ndk版本不一致才会出现这个问题

**Comment by jenly1314** [comment]
既然知道了两个库中的libc++_shared.so不一样，解决不了，可以另辟蹊径，换个库吧，readme有其他扫码库推荐，用法基本一致。

**Comment by lantee** [comment]
好的 谢谢解答！
