### ISSUE TITLE
扫码Crash,是什么原因呢

### ISSUE THREAD

**Issue by leishiyu** [jenly1314/WeChatQRCode#40]
CvException [org.opencv.core.CvException: OpenCV(4.6.0) /home/king/work/opencv/opencv-4.6.0/modules/core/src/alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 1228800 bytes in function 'OutOfMemoryError'
]

**Comment by jenly1314** [comment]
[OOM](https://github.com/jenly1314/MLKit/issues/39)
