### ISSUE TITLE
Crash When open WeChatCameraScanActivity

### ISSUE THREAD

**Issue by thongvo109** [jenly1314/WeChatQRCode#44]
I did rebuild project but it doesn't work. Please help me :( 

<img width="1473" alt="Screenshot 2024-01-04 at 14 17 13" src="https://github.com/jenly1314/WeChatQRCode/assets/64881072/3ae2254d-d7bd-4710-bce7-84b7a3642238">

**Comment by jenly1314** [comment]
> I did rebuild project but it doesn't work. Please help me :(
> 
> <img alt="Screenshot 2024-01-04 at 14 17 13" width="1473" src="https://private-user-images.githubusercontent.com/64881072/294111361-3ae2254d-d7bd-4710-bce7-84b7a3642238.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTg0MzEsIm5iZiI6MTcwNDM1ODEzMSwicGF0aCI6Ii82NDg4MTA3Mi8yOTQxMTEzNjEtM2FlMjI1NGQtZDdiZC00NzEwLWJjZTctODRiN2EzNjQyMjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA4NDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZTRjZWI3MTFmN2Q3YjYyOGQyOGVkOTA0NjRjYmI2MjNkNDc1YTk5ZTMwNzU0NDNiZTI5MzNkYzgzYWNiY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dM_LlQQpKqco53UNoFRaVOqrKtbuxqpz2i0_0rN8VKw">

Please confirm which version of Gradle you are currently using?
