### ISSUE TITLE
arm64-v8a平台，进入扫描界面过几秒app挂了

### ISSUE THREAD

**Issue by konkong** [jenly1314/WeChatQRCode#49]
03-30 11:51:23.370 E/cv::error()(32381): OpenCV(4.9.0) Error: Requested object was not found (could not open directory: /data/app/***-RNwWSDNOyjf7H-aDC_PxVg==/base.apk!/lib/arm64-v8a) in glob_rec, file /home/king/work/opencv/opencv-4.9.0/modules/core/src/glob.cpp, line 279

**Comment by jenly1314** [comment]
> 03-30 11:51:23.370 E/cv::error()(32381): OpenCV(4.9.0) Error: Requested object was not found (could not open directory: /data/app/***-RNwWSDNOyjf7H-aDC_PxVg==/base.apk!/lib/arm64-v8a) in glob_rec, file /home/king/work/opencv/opencv-4.9.0/modules/core/src/glob.cpp, line 279

我测试是正常的，有其他关键信息要补充的吗？

**Comment by jenly1314** [comment]
```java
OpenCV.initOpenCV();
WeChatQRCodeDetector.init(this);
```

这个初始化放错地方了，需要提前初始化，建议放到 `MainActivity`，**WeChatCameraScanActivity**  里面都已经开始使用了，你再初始化，顺序错了。

**Comment by konkong** [comment]
> ```java
> OpenCV.initOpenCV();
> WeChatQRCodeDetector.init(this);
> ```
> 
> 这个初始化放错地方了，需要提前初始化，建议放到 `MainActivity`，**WeChatCameraScanActivity** 里面都已经开始使用了，你再初始化，顺序错了。

我重新放置到MainActivity里，再次进入扫描界面还是会报一样的错误

**Comment by konkong** [comment]
找到原因了，是由于我还引入了百度地图库，导致两个libc++_shared.so冲突

当时看到这个编译错误，直接使用下面方法保留了一个
刚才比较看编译最终将百度地图库中的libc++_shared.so打包进apk了
我将百度地图库中的libc++_shared.so删了就ok了
```
packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }
```

**Comment by jenly1314** [comment]
> 找到原因了，是由于我还引入了百度地图库，导致两个libc++_shared.so冲突
> 
> 当时看到这个编译错误，直接使用下面方法保留了一个 刚才比较看编译最终将百度地图库中的libc++_shared.so打包进apk了 我将百度地图库中的libc++_shared.so删了就ok了
> 
> ```
> packagingOptions {
>         pickFirst 'lib/x86/libc++_shared.so'
>         pickFirst 'lib/x86_64/libc++_shared.so'
>         pickFirst 'lib/arm64-v8a/libc++_shared.so'
>         pickFirst 'lib/armeabi-v7a/libc++_shared.so'
>     }
> ```

好的，记得关掉此问题。
