### ISSUE TITLE
大佬可以给一个利用wechat生成二维码的工具类

### ISSUE THREAD

**Issue by Jeffery336699** [jenly1314/WeChatQRCode#50]
现在想把项目中的所有zxing相关的代码替换为wechat，但是发现zxing生成二维码这个地方好像wechat没有直接可用的。大佬，可以提供一个方法吗？🥰🥰万分感谢~

**Comment by jenly1314** [comment]
> 现在想把项目中的所有zxing相关的代码替换为wechat，但是发现zxing生成二维码这个地方好像wechat没有直接可用的。大佬，可以提供一个方法吗？🥰🥰万分感谢~

**opencv** 中没找到生成二维码相关的方法，用zxing生成二维码挺好的。
