### ISSUE TITLE
大佬，平行视窗不支持，扫码画面没法跟随横竖屏切换

### ISSUE THREAD

**Issue by Jeffery336699** [jenly1314/WeChatQRCode#51]
引入平行视窗，预览画面没法跟随平行视窗切换，大佬，没木有办法

**Comment by jenly1314** [comment]
> 引入平行视窗，预览画面没法跟随平行视窗切换，大佬，没木有办法

这跟`WeChatQRCode`有关系吗？是你需去处理适配问题吧。
