### ISSUE TITLE
wechat如何输出二维码四个角点

### ISSUE THREAD

**Issue by REcounting** [jenly1314/WeChatQRCode#52]
您好，您试过用opencv的wechat扫描如何输出二维码的四个角点吗，我只能看到一个矩形框

**Comment by jenly1314** [comment]
> 您好，您试过用opencv的wechat扫描如何输出二维码的四个角点吗，我只能看到一个矩形框

**README** 有相应的说明与代码示例，完全不看的？

**Comment by REcounting** [comment]
> > 您好，您试过用opencv的微信扫描如何输出二维码的四个角点吗，我只能看到一个矩形框
> 
> **README** 有相应的说明与代码示例，完全不看的？

错了，哥，我看了那个opencv的wechat文档没有，咱们这个readme确实没看，错了，哥

**Comment by REcounting** [comment]
> > > 您好，您试过用opencv的微信扫描如何输出二维码的四个角点吗，我只能看到一个矩形框
> > 
> > 
> > **README** 有相应的说明与代码示例，完全不看的？
> 
> 错了，哥，我看了那个opencv的wechat文档没有，咱们这个readme确实没看，错了，哥

好像您的结论也是wechat识别出来是矩形框，并不是二维码的四个角点位置
