### ISSUE TITLE
linux版本GLIBC_2.29'问题

### ISSUE THREAD

**Issue by wtt40122** [jenly1314/WeChatQRCode#53]
当我在linux上运行时，一直报有个组件版本不支持的问题，但我尝试升级后也是不能改变这个问题
Caused by: java.lang.UnsatisfiedLinkError: /tmp/[opencv_java49010648016418230842407.so](http://opencv_java49010648016418230842407.so/): /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/[opencv_java49010648016418230842407.so](http://opencv_java49010648016418230842407.so/))

java版本，直接把集成到我自己的服务中遇到了这个问题

**Comment by jenly1314** [comment]
> 当我在linux上运行时，一直报有个组件版本不支持的问题，但我尝试升级后也是不能改变这个问题 Caused by: java.lang.UnsatisfiedLinkError: /tmp/[opencv_java49010648016418230842407.so](http://opencv_java49010648016418230842407.so/): /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/[opencv_java49010648016418230842407.so](http://opencv_java49010648016418230842407.so/))
> 
> java版本，直接把集成到我自己的服务中遇到了这个问题

- 有CI记录的：[CircleCI Checks](https://github.com/jenly1314/WeChatQRCode/runs/20931484143)；
- 请确保是按照readme里说明的使用步骤去集成的；
-  WeChatQRCode中提供的 **lib** 文件夹里就那么几个文件，你这 `opencv_java49010648016418230842407.so` 是从哪里来的？

**Comment by wtt40122** [comment]
> > 当我在linux上运行时，一直报有个组件版本不支持的问题，但我尝试升级后也是不能改变这个问题 Caused by: java.lang.UnsatisfiedLinkError: /tmp/[opencv_java49010648016418230842407.so](http://opencv_java49010648016418230842407.so/): /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/[opencv_java49010648016418230842407.so](http://opencv_java49010648016418230842407.so/))
> > java版本，直接把集成到我自己的服务中遇到了这个问题
> 
> * 有CI记录的：[CircleCI Checks](https://github.com/jenly1314/WeChatQRCode/runs/20931484143)；
> * 请确保是按照readme里说明的使用步骤去集成的；
> * WeChatQRCode中提供的 **lib** 文件夹里就那么几个文件，你这 `opencv_java49010648016418230842407.so` 是从哪里来的？

是的，我是按文档中步骤走完的，我的是maven进行版本控制，不是gradle，我在windows上都已经执行没问题了，且打成jar包也执行没问题，windows那个dll文件执行也是ok，只有当我打成jar包后在linux上执行出现这个问题。这个文件时因为我把它放在resouces文件下了，当打包后是一个jar包，所以会在临时目录中拷贝出需要使用的文件，文件名加了随机数，2个文件是一样的，我已经在程序中执行了md5校验检查

**Comment by jenly1314** [comment]
- 上面提到的CI的目的就是在linux环境下执行了单元测试并且结果是成功的。
- 那个错误提示：关于找不到 **GLIBC_2.29** 的问题；你可以尝试先安装或更新下：glibc这个库（要求至少是v2.29版本）

**Comment by wtt40122** [comment]
> * 上面提到的CI的目的就是在linux环境下执行了单元测试并且结果是成功的。
> * 那个错误提示：关于找不到 **GLIBC_2.29** 的问题；你可以尝试先安装或更新下：glibc这个库（要求至少是v2.29版本）

是的，我一直在尝试升级这个这个库，底层用的系统还有一些问题，也是正在寻求解决方法

**Comment by wtt40122** [comment]
已经解决了，使用了openjdk:11基础镜像就可以的

**Comment by wtt40122** [comment]
请问下java版本怎么分析二维码了，就是一个图片中有多个二维码，我可以知道多个二维码的所在的位置

**Comment by jenly1314** [comment]
> 请问下java版本怎么分析二维码了，就是一个图片中有多个二维码，我可以知道多个二维码的所在的位置

Java版本只是集成步骤不一样，使用方式跟Android版本基本上是一样的，你可以参考主分支上`README`的使用说明。

**Comment by wtt40122** [comment]
> > 请问下java版本怎么分析二维码了，就是一个图片中有多个二维码，我可以知道多个二维码的所在的位置
> 
> Java版本只是集成步骤不一样，使用方式跟Android版本基本上是一样的，你可以参考主分支上`README`的使用说明。

好的，谢谢
