### ISSUE TITLE
咨询一个技术问题，有种特殊二维码，扫码可以，一旦用相册上传就解析不出来

### ISSUE THREAD

**Issue by velentZ** [jenly1314/WeChatQRCode#55]
是不是和角度有关系？或者说摄像头有什么特殊处理吗？

**Comment by jenly1314** [comment]
> 是不是和角度有关系？或者说摄像头有什么特殊处理吗？

* 并没有什么特殊处理，只是输入源不一样；主要是存在一些客观因素的影响，包括但不限于：环境、角度、识别区域、图片大小等等。
* 通过扫码识别时，此时输入源为拍摄的图像帧，这些客观因素都是变量，在没识别成功前，会多次进行识别；并且只需识别成功一次即可；而从相册选择图片进行识别时，此时输入源为选择的的图片，这些客观因素都相对固定。所以就算是识别同一张图片二维码，也会因为选择的识别方式不同，而影响到最终的结果。
