### ISSUE TITLE
jdk版本问题

### ISSUE THREAD

**Issue by atgtahub** [jenly1314/WeChatQRCode#58]
是否可以支持低版本的jdk，比如jdk8，目前最新版的包需要jdk11以上

**Comment by jenly1314** [comment]
> 是否可以支持低版本的jdk，比如jdk8，目前最新版的包需要jdk11以上

[编译版本](https://github.com/jenly1314/WeChatQRCode/blob/master/wechat-qrcode/build.gradle#L26-L28)一直用的是JDK8；你说的是Gradle JDK的版本吧；Gradle JDK版本现在应该都用JDK17或JDK21了吧。
