### ISSUE TITLE
开放的api有点少

### ISSUE THREAD

**Issue by 643063150** [jenly1314/WeChatQRCode#8]
扫描速度是没的说的，但是开放的api感觉有点少，比如识别到二维码的坐标位置，二维码在屏幕中的大小之类的，要做镜头的自动放大缩小但是获取不到这些数据感觉也有点难搞 或许是我没找到？  zxing中是会返回这些数据或者根据数据自己计算出来  只是建议

**Comment by jenly1314** [comment]
看下 **WeChatQRCodeDetector** 这个类
