### ISSUE TITLE
还需要安装opencv吗？报如下错误

### ISSUE THREAD

**Issue by csh159** [jenly1314/WeChatQRCode#9]
![1635828242(1)](https://user-images.githubusercontent.com/4157414/139788168-ae12527e-b0a9-47b6-bc3c-2c74bbcd4760.png)

**Comment by jenly1314** [comment]
看你这个报错日志，是 **dialog.show()** 时，所依赖的父窗口，即当前的Activity可能没有运行导致的。

**Comment by jenly1314** [comment]
看你这个报错日志，是 **dialog.show()** 时，所依赖的父窗口，即当前的Activity可能没有运行导致的。
你可以通过 **README** 中的链接下载演示App试试是否正常。

**Comment by csh159** [comment]
问题解决了，谢谢回复
